### ISSUE TITLE
Status icon not visible (probably conflict with resharper)

### ISSUE THREAD

**Issue by micdenny** [onlyutkarsh/VSOStatusInspector#1]
I've installed the extension from visual studio 2013 update 4:

![image](https://cloud.githubusercontent.com/assets/1633595/7682595/6e4affa8-fd79-11e4-9b65-9398b9f90705.png)

but after the vs restart, I don't see any icon, and I suspect is because I have resharper installed, that it also has an icon, or probably in conflict with other extension don't know.

![image](https://cloud.githubusercontent.com/assets/1633595/7682639/cd13ad14-fd79-11e4-9762-980e0eca859b.png)

![image](https://cloud.githubusercontent.com/assets/1633595/7682647/e0713cd2-fd79-11e4-9e4b-a0b9e9fe47df.png)

when a solution is opened you can see the resharper icon:

![image](https://cloud.githubusercontent.com/assets/1633595/7682662/fa3a7174-fd79-11e4-9720-0f9c64f87cb8.png)

**Comment by onlyutkarsh** [comment]
Hello Michael,

Thanks for reporting this issue. I use resharper as well and I have not had this issue. So I do not think it is caused by resharper. When solution is loaded, the animation area is in the middle beside Line number (you can build your solution to see the build icon - that is where the animation area). Can you please check whether icon is displayed in the middle?
![2015-05-18_154508](https://cloud.githubusercontent.com/assets/2685029/7683154/1a0cf788-fd75-11e4-9e7a-15a228b25645.png)

Meanwhile, i will investigate from my side too. BTW, what OS version are you using? Is it Win 8 / Win 10?

**Comment by micdenny** [comment]
OS: Win 8.1 pro

I realize now that I don't see the build animation icon, but a build progress bar instead:

![image](https://cloud.githubusercontent.com/assets/1633595/7684340/7ade15f0-fd85-11e4-8efc-7df0fb610c46.png)

need to investigate which plugin is doing this, and if is a plugin... :smile:

**Comment by micdenny** [comment]
It's the `Enable rich client visual experience`:

![image](https://cloud.githubusercontent.com/assets/1633595/7684428/2e7db87c-fd86-11e4-997b-d2dad4dcd923.png)

now I see the build:

![image](https://cloud.githubusercontent.com/assets/1633595/7684421/1ffe6198-fd86-11e4-9433-b4a60eae31fb.png)

and the vso status inspector as well (currently investigating the problem LoL):

![image](https://cloud.githubusercontent.com/assets/1633595/7684440/3d86e7b2-fd86-11e4-97db-1b2bc6372dca.png)

I think this should be add the package description, and in the github readme page, but better could be if it's possible to move that icon somewhere else, or manage the `Enable rich client visual experience` and use text instead of icon when rich client is disabled. What do you think?

**Comment by onlyutkarsh** [comment]
Brilliant! That is a good find! Thanks for finding and sharing the root cause for it. I can replicate the issue now too. 
Regarding, showing text when `Enable rich client visual experience` is enabled, I am sceptical using the  text as it gets overwritten whenever you are building or editing the code. That is because VS actively uses it to update the information. Also, user might not like it if I constantly keep writing the status there as it might hide the useful information user wants to see. Right?

**Comment by micdenny** [comment]
> I agree that it needs to be in github readme and in the package help file.

I think this could be enough for now.
